### ISSUE TITLE
Able to style formulas with text aligned right?

### ISSUE THREAD

**Issue by Payge** [kexanie/MathView#14]
Hello there,

Thanks for Mathview, it's been very helpful for styling math formulas so far :)

I wanted to know if there is a way to have a MathView style itself so it is right to left? or text aligned right? 

Thanks for the great library!

**Comment by jianzhongli** [comment]
Hello @Payge , you can tweak `MathJax` with more configuration by calling `MathView.config()`, for example, to right align your formula, you can call 

``` java
MathView.config("MathJax.Hub.Config({\n" +
    "jax: [\"input/TeX\",\"output/HTML-CSS\"],\n" + 
    "displayAlign: \"right\"});"
);
```

This will effectively insert the configuration statement into the html document which your `MathView` formula is embedded in. Please check MathJax's [document](http://docs.mathjax.org/en/latest/configuration.html) if you want more options.

**Comment by BunnyCinnamon** [comment]
MathJax is slow for me tho, 1 second to format and align the text, looks bad :/ and I dont think Katex has that... :<
