### ISSUE TITLE
Not Show "A" character on Lenovo P780 running Android 4.2.1 (API 17)

### ISSUE THREAD

**Issue by iqbalhafidh** [kexanie/MathView#2]
Not Show "A" character on Lenovo P780 running Android 4.2.1 (API 17) 
it make me crazy, because it just "A" Character and NOT for another character

my Tex look like this : 

$${ A }_{ 1 }=\frac { \pi { d }_{ 1 }^{ 2 } }{ 4 } $$

<img width="565" alt="a - character problem" src="https://cloud.githubusercontent.com/assets/10403148/11320199/226e6cae-90c3-11e5-96ee-a7f49096b468.png">

And then it show up like this

<img src="https://cloud.githubusercontent.com/assets/10403148/11320201/2ff16c28-90c3-11e5-867e-8aebea076a6a.png" width="250">

Where's my A Character??

!@#$%^&*()

Need Help

Thanks

**Comment by kexanie** [comment]
@iqbalhafidh Thank you for your feedback. You will be notified when the bug is fixed.

**Comment by kexanie** [comment]
@iqbalhafidh After some investigation, I found that it's a konwn bug of MathJax on Android `WebView`. The native `WebView` failed to read the provided `.woff` fonts correctly and the issue remains unsolved in the latest official version of MathJax. 

Fortunately someone came up with a solution. I have already replaced the `.woff` font files with tweaked `.otf` files and pushed an updated version of `MathView` to jcenter. You can switch the dependency version to `0.0.2` (`compile 'io.github.kexanie.library:MathView:0.0.2'`). The character 'A' should be normal now.

Reference:
1. https://github.com/mathjax/MathJax/issues/403
2. https://github.com/mathjax/MathJax/issues/369
3. https://groups.google.com/forum/#!msg/mathjax-users/j0ohai-plEM/_if2-RBBdNUJ

**Comment by iqbalhafidh** [comment]
Great.. It works now

![device-2015-11-22-161835](https://cloud.githubusercontent.com/assets/10403148/11322952/d0d5bf10-9134-11e5-9845-67eebc28ba38.png)

Thanks kexanie for fastest response
