### ISSUE TITLE
Unable to downlaod .aar file from bintray

### ISSUE THREAD

**Issue by Zoha131** [kexanie/MathView#21]
There is no download link in the page 

> https://bintray.com/kexanie/maven/MathView/0.0.6

how can I download .aar file? Please help me.

**Comment by jianzhongli** [comment]
have a look on this: [https://bintray.com/kexanie/maven/MathView/0.0.6#files/io/github/kexanie/library/MathView/0.0.6](https://bintray.com/kexanie/maven/MathView/0.0.6#files/io/github/kexanie/library/MathView/0.0.6)

**Comment by Zoha131** [comment]
[image: Capture.PNG]I have visited that page. But there is no link to
download.
