### ISSUE TITLE
Unable to add newline

### ISSUE THREAD

**Issue by Zoha131** [kexanie/MathView#22]
I am absolutely new in programming. 

I have googled but the solutions show how to add new line in MathJax but that method didn't work in MathView.  I have tried this

> http://meta.math.stackexchange.com/questions/11720/new-line-within-mathjax

But that didn't work. 
Please help me.

**Comment by Zoha131** [comment]
I have solved the problem. What I have learned that every '\\' character needs to be escaped in Java code.
So to have a new line I must have to add '\\\\' instead of '\\'.

**Comment by sudhanshunathmishra** [comment]
Hi, could you please clarify how you added newline? 
I have tried '\', '\\', \\\\' with no avail for both MathJax and KaTex

**Comment by Zoha131** [comment]
try this '\\\\\\\\' four '\\'.
