### ISSUE TITLE
Unclicable webview

### ISSUE THREAD

**Issue by DrunkenElf** [kexanie/MathView#68]
![image](https://user-images.githubusercontent.com/33663807/55292833-fa20ec80-53f7-11e9-8b6f-c47f1ea9a0fc.png)
Please, can you make it to return true. I could do it by myself but there is no jar library. I need to listen to clicking to different parts of webview.
Thanks for attention.

**Comment by DrunkenElf** [comment]
Oh, I've found .aar file

**Comment by pranavpari** [comment]
Are you able to do it?

**Comment by rahulsain-ingeniumedu** [comment]
I want to copy html text instead of rendered text is it possible?

@DrunkenElf
