### ISSUE TITLE
Does this library supports Javafx Application?

### ISSUE THREAD

**Issue by rajendraprasad348** [kexanie/MathView#74]
I have tried to run jar files mentioned in Bintray but it is giving an no main manifest attribute error.
then how to use jar files in my javafx application ? Please help me out of this problem

**Comment by jianzhongli** [comment]
This is a Android library, I don't think it will run in javafx. Is there anything like `WebView` in javafx? Maybe  you can tweak the source code a little bit to make it work in javafx.

**Comment by rajendraprasad348** [comment]
@jianzhongli yes we have webview in javafx. i am also new to javafx i dont know how to modify it.
